name: Delete Old Issues

on:
  schedule:
    - cron: '0 0 */3 * *' # Run every 3 days at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  delete-old-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      
    steps:
      - name: Delete issues older than 1 week
        uses: actions/github-script@v7
        with:
          script: |
            const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
            const { data: issues } = await github.rest.issues.listForRepo({
              ...context.repo,
              state: 'open'
            });
            
            for (const issue of issues) {
              if (issue.pull_request || new Date(issue.created_at) >= weekAgo) continue;
              
              try {
                await github.rest.issues.delete({ ...context.repo, issue_number: issue.number });
              } catch {
                await github.rest.issues.update({ ...context.repo, issue_number: issue.number, state: 'closed' });
              }
            }
